topic:
  name: regis-avro

server:
  port: 8181

spring:
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      acks: "all"  # Configuração para acks
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
        enable:
          idempotence: true  # Configuração para idempotência