topic:
  name: regis-avro

server:
  port: 8182


spring:
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    consumer:
      group-id: "regis-new"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
        specific:
          avro:
            reader: "true"